// Export everything from the emulator components package so the frontend can import it
export { BaseComponent } from './BaseComponent';
export { default as wokwiLed } from './wokwi-led';
export { default as wokwiArduinoUno } from './wokwi-arduino-uno';
export { default as wokwiRaspberryPiPico } from './wokwi-raspberry-pi-pico/index.ts';
export { default as wokwiRaspberryPiPicoW } from './wokwi-raspberry-pi-pico-w/index.ts';
export { default as wokwiResistor } from './wokwi-resistor';
export { default as wokwiPushbutton } from './wokwi-pushbutton';
export { default as wokwiPowerSupply } from './wokwi-power-supply';
export { default as wokwiNeopixelMatrix } from './wokwi-neopixel-matrix';
export { default as wokwiBuzzer } from './wokwi-buzzer';
export { default as wokwiMotor } from './wokwi-motor';
export { default as openhwServo } from './wokwi-servo';
export { default as wokwiMotorDriver } from './wokwi-motor-driver';
export { default as wokwiSlidePotentiometer } from './wokwi-slide-potentiometer';
export { default as wokwiPotentiometer } from './wokwi-potentiometer';
export { default as shiftRegister } from './shift_register';
export { default as openhwMax7219 } from './wokwi-max7219';
export { default as openhwSSD1306Oled } from './wokwi-ssd1306-oled';
export { default as openhw7Segment } from './wokwi-7segment';
export { default as openhwIli9341 } from './wokwi-ili9341';
export { default as openhwLcd2004I2C } from './wokwi-lcd2004-i2c';
export { default as openhwLcd1602I2C } from './wokwi-lcd1602-i2c';
export { default as openhwLdrModule } from './wokwi-ldr-module';
export { default as max30102 } from './max30102';
export { default as openhwSdCard } from './wokwi-sd-card';
export { default as openhwMembraneKeypad } from './wokwi-membrane-keypad';
export { default as openhwAnalogJoystick } from './wokwi-analog-joystick';
export { default as openhwTm16377Segment } from './wokwi-tm1637-7segment';
export { default as wokwiNeopixelRing } from './wokwi-neopixel-ring';
export { default as wokwiBreadboard } from './wokwi-breadboard';
export { default as wokwiBreadboardHalf } from './wokwi-breadboard-half';
export { default as wokwiBreadboardMini } from './wokwi-breadboard-mini';
export { default as openhwA4988 } from './wokwi-a4988';
export { default as openhwStepperMotor } from './wokwi-stepper-motor';
export { default as openhwNLSF595 } from './wokwi-nlsf595';
export { default as openhwCD74HC4067 } from './wokwi-cd74hc4067';
export { default as openhwL293D } from './wokwi-l293d';
export { default as openhwRGBLED } from './wokwi-rgb-led';
export { default as openhwRotaryEncoder } from './wokwi-rotary-encoder';
export { default as openhwLogicAnalyzer } from './wokwi-logic-analyzer';
export { default as openhwNokia5110 } from './wokwi-nokia-5110';
export { default as openhwSoilMoistureSensor } from './wokwi-soil-moisture-sensor';
export { default as wokwiNpnTransistor } from './wokwi-npn-transistor';
export { default as wokwiDiode } from './wokwi-diode';
export { default as wokwiPhotodiode } from './wokwi-photodiode';
export { default as openhwPCA9685 } from './wokwi-pca9685';
export { default as openhwPCA9865 } from './wokwi-pca9865';
export { default as wokwiArduinoSensorShield } from './wokwi-arduino-sensor-shield';
export { default as wokwiArduinoNano } from './wokwi-arduino-nano';
export { default as wokwiBattery } from './wokwi-battery';
export { default as wokwiCharger } from './wokwi-charger';
export { default as wokwiPhotoresistor } from './wokwi-photoresistor';
export { default as wokwiNtcTemperatureSensor } from './wokwi-ntc-temperature-sensor';
export { default as openhwBmp180 } from './wokwi-bmp180';
export { default as openhwDs1307Rtc } from './wokwi-ds1307-rtc';
export { default as openhwMpu6050 } from './wokwi-mpu6050';
export { default as wokwiNtcThermistor } from './wokwi-ntc-thermistor';
export { default as openhwRelayModule } from './wokwi-relay-module';


export { default as logicMux2to1 } from './logic-mux-2to1';
export { default as logicDFlipFlop } from './logic-d-flipflop';
export { default as logicDFlipFlopR } from './logic-d-flipflop-r';
export { default as logicDFlipFlopDsr } from './logic-d-flipflop-dsr';
export { default as logicClockGenerator } from './logic-clock-generator';
export { default as logicIc74xx } from './logic-ic-74xx';
export { default as wokwiArduinoMega } from './wokwi-arduino-mega';
export { default as wokwiAttiny85 } from './wokwi-attiny85';
export { default as openhwHcSr04 } from './wokwi-hc-sr04';

export { FullCircuitValidator, analyzeCodeHardwareSync, ProtocolAnalyzer, runUnifiedValidation } from '../circuit-validation/index.js';

